
// import type { Metadata } from "next";
// import { Nunito } from "next/font/google";
// import { ClerkProvider } from '@clerk/nextjs';
// import { Toaster } from "@/components/ui/sonner";
// import { ExitModal } from "@/components/modals/exit-modal";
// import { HeartsModal } from "@/components/modals/hearts-modal";
// import { PracticeModal } from "@/components/modals/practice-modal";
// import "./globals.css";

// // Import Nunito from Google Fonts
// const font  = Nunito({
//   subsets: ["latin"], // Define the subsets you want to use
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={`${font.className} antialiased`}>
//         <Toaster />
//         {children}
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }











import type { Metadata } from "next";
import { Varela_Round } from "next/font/google";

import {
  ClerkProvider,
  // SignInButton,
  // SignedIn,
  // SignedOut,
  // UserButton,
} from "@clerk/nextjs";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ExitModal } from "@/components/modals/exit-modal";
import { HeartsModal } from "@/components/modals/hearts-modal";
import { PracticeModal } from "@/components/modals/practice-modal";

const Varela = Varela_Round({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Lingoo...",
  description: "Learn, practice and master new languages with Lingoo.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={Varela.className}>
          <Toaster />
          <ExitModal />
          <HeartsModal />
          <PracticeModal />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}

